version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - curl -sSL https://install.python-poetry.org | python3.10 -
      - pip install awscli
  pre_build:
    commands:
      - poetry install --no-dev
  build:
    commands:
      - alembic upgrade head
