version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install poetry
      - pip install awscli
  pre_build:
    commands:
      - poetry install --no-root --only main
  build:
    commands:
      - alembic upgrade head
