version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install poetry
  pre_build:
    commands:
      - poetry install
  build:
    commands:
      - poetry run alembic upgrade head
